### ISSUE TITLE
Test Azure OpenAI (v1) Python SDK

### ISSUE THREAD

**Issue by iMicknl** [pascalvanderheiden/ais-apim-openai#13]
- [ ] Test Azure OpenAI (v1) Python SDK
- [ ] Add samples

**Comment by iMicknl** [comment]
For now I face `InternalServerError: Error code: 500` when I use the Python V1 SDK. Via the REST API the same request does work.

```python3
import os
from openai import AzureOpenAI

os.environ["AZURE_OPENAI_API_BASE"] = "https://apim-xxx.azure-api.net"
os.environ["AZURE_OPENAI_KEY"] = "" # Marketing key

client = AzureOpenAI(
    azure_endpoint = os.getenv("AZURE_OPENAI_API_BASE"),
    api_key = os.getenv("AZURE_OPENAI_KEY"),
    api_version = os.getenv("OPENAI_API_VERSION", "2023-09-01-preview")
)

response = client.chat.completions.create(
    model = "gpt-35-turbo", # model = "Azure OpenAI deployment name".
    messages = [
        {"role": "system", "content": "You are a friendly chatbot"},
        {"role": "user", "content": "Choose a random planet and describe it to me in 3 sentences."}
    ],
    stream = False
)

print(response.choices[0].message.content)

```

will raise an error in the proxy:

```
 System.FormatException: Cannot add value because header 'Authorization' does not support multiple values.
         at System.Net.Http.Headers.HttpHeaders.ParseAndAddValue(HeaderDescriptor descriptor, HeaderStoreItemInfo info, String value)
         at System.Net.Http.Headers.HttpHeaders.Add(HeaderDescriptor descriptor, String value)
         at Azure.OpenAI.ChargebackProxy.ReverseProxy.OpenAIChargebackTransformProvider.<Apply>b__8_0(RequestTransformContext requestContext) in /src/Azure.OpenAI.ChargebackProxy/ReverseProxy/OpenAIChargebackTransformProvider.cs:line 57
         at Yarp.ReverseProxy.Transforms.Builder.StructuredTransformer.TransformRequestAsync(HttpContext httpContext, HttpRequestMessage proxyRequest, String destinationPrefix, CancellationToken cancellationToken)
         at Yarp.ReverseProxy.Forwarder.HttpForwarder.CreateRequestMessageAsync(HttpContext context, String destinationPrefix, HttpTransformer transformer, ForwarderRequestConfig requestConfig, Boolean isStreamingRequest, ActivityCancellationTokenSource activityToken)
         at Yarp.ReverseProxy.Forwarder.HttpForwarder.SendAsync(HttpContext context, String destinationPrefix, HttpMessageInvoker httpClient, ForwarderRequestConfig requestConfig, HttpTransformer transformer, CancellationToken cancellationToken)
fail: Microsoft.AspNetCore.Server.Kestrel[13]
      Connection id "0HN07NNSGJGQV", Request id "0HN07NNSGJGQV:00000001": An unhandled exception was thrown by the application.
      System.NullReferenceException: Object reference not set to an instance of an object.
         at Azure.OpenAI.ChargebackProxy.ReverseProxy.OpenAIChargebackTransformProvider.<Apply>b__8_1(ResponseTransformContext responseContext) in /src/Azure.OpenAI.ChargebackProxy/ReverseProxy/OpenAIChargebackTransformProvider.cs:line 63
         at Yarp.ReverseProxy.Transforms.Builder.StructuredTransformer.TransformResponseAsync(HttpContext httpContext, HttpResponseMessage proxyResponse, CancellationToken cancellationToken)
         at Yarp.ReverseProxy.Forwarder.HttpForwarder.<>c__DisplayClass13_0.<<HandleRequestFailureAsync>g__ReportErrorAsync|0>d.MoveNext()
      --- End of stack trace from previous location ---
         at Yarp.ReverseProxy.Forwarder.HttpForwarder.HandleRequestFailureAsync(HttpContext context, StreamCopyHttpContent requestContent, Exception requestException, HttpTransformer transformer, ActivityCancellationTokenSource requestCancellationSource, Boolean failedDuringRequestCreation)
         at Yarp.ReverseProxy.Forwarder.HttpForwarder.SendAsync(HttpContext context, String destinationPrefix, HttpMessageInvoker httpClient, ForwarderRequestConfig requestConfig, HttpTransformer transformer, CancellationToken cancellationToken)
         at Yarp.ReverseProxy.Forwarder.ForwarderMiddleware.Invoke(HttpContext context)
         at Yarp.ReverseProxy.Health.PassiveHealthCheckMiddleware.Invoke(HttpContext context)
         at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
         at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.ProcessRequests[TContext](IHttpApplication`1 application)
warn: Yarp.ReverseProxy.Forwarder.HttpForwarder[48]
      RequestCreation: An error was encountered while creating the request message.
      System.FormatException: Cannot add value because header 'Authorization' does not support multiple values.
         at System.Net.Http.Headers.HttpHeaders.ParseAndAddValue(HeaderDescriptor descriptor, HeaderStoreItemInfo info, String value)
         at System.Net.Http.Headers.HttpHeaders.Add(HeaderDescriptor descriptor, String value)
         at Azure.OpenAI.ChargebackProxy.ReverseProxy.OpenAIChargebackTransformProvider.<Apply>b__8_0(RequestTransformContext requestContext) in /src/Azure.OpenAI.ChargebackProxy/ReverseProxy/OpenAIChargebackTransformProvider.cs:line 57
         at Yarp.ReverseProxy.Transforms.Builder.StructuredTransformer.TransformRequestAsync(HttpContext httpContext, HttpRequestMessage proxyRequest, String destinationPrefix, CancellationToken cancellationToken)
         at Yarp.ReverseProxy.Forwarder.HttpForwarder.CreateRequestMessageAsync(HttpContext context, String destinationPrefix, HttpTransformer transformer, ForwarderRequestConfig requestConfig, Boolean isStreamingRequest, ActivityCancellationTokenSource activityToken)
         at Yarp.ReverseProxy.Forwarder.HttpForwarder.SendAsync(HttpContext context, String destinationPrefix, HttpMessageInvoker httpClient, ForwarderRequestConfig requestConfig, HttpTransformer transformer, CancellationToken cancellationToken)
fail: Microsoft.AspNetCore.Server.Kestrel[13]
      Connection id "0HN07NNSGJGQV", Request id "0HN07NNSGJGQV:00000002": An unhandled exception was thrown by the application.
      System.NullReferenceException: Object reference not set to an instance of an object.
         at Azure.OpenAI.ChargebackProxy.ReverseProxy.OpenAIChargebackTransformProvider.<Apply>b__8_1(ResponseTransformContext responseContext) in /src/Azure.OpenAI.ChargebackProxy/ReverseProxy/OpenAIChargebackTransformProvider.cs:line 63
         at Yarp.ReverseProxy.Transforms.Builder.StructuredTransformer.TransformResponseAsync(HttpContext httpContext, HttpResponseMessage proxyResponse, CancellationToken cancellationToken)
         at Yarp.ReverseProxy.Forwarder.HttpForwarder.<>c__DisplayClass13_0.<<HandleRequestFailureAsync>g__ReportErrorAsync|0>d.MoveNext()
      --- End of stack trace from previous location ---
         at Yarp.ReverseProxy.Forwarder.HttpForwarder.HandleRequestFailureAsync(HttpContext context, StreamCopyHttpContent requestContent, Exception requestException, HttpTransformer transformer, ActivityCancellationTokenSource requestCancellationSource, Boolean failedDuringRequestCreation)
         at Yarp.ReverseProxy.Forwarder.HttpForwarder.SendAsync(HttpContext context, String destinationPrefix, HttpMessageInvoker httpClient, ForwarderRequestConfig requestConfig, HttpTransformer transformer, CancellationToken cancellationToken)
         at Yarp.ReverseProxy.Forwarder.ForwarderMiddleware.Invoke(HttpContext context)
         at Yarp.ReverseProxy.Health.PassiveHealthCheckMiddleware.Invoke(HttpContext context)
         at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
         at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.ProcessRequests[TContext](IHttpApplication`1 application)
warn: Yarp.ReverseProxy.Forwarder.HttpForwarder[48]
      RequestCreation: An error was encountered while creating the request message.
      System.FormatException: Cannot add value because header 'Authorization' does not support multiple values.
         at System.Net.Http.Headers.HttpHeaders.ParseAndAddValue(HeaderDescriptor descriptor, HeaderStoreItemInfo info, String value)
         at System.Net.Http.Headers.HttpHeaders.Add(HeaderDescriptor descriptor, String value)
         at Azure.OpenAI.ChargebackProxy.ReverseProxy.OpenAIChargebackTransformProvider.<Apply>b__8_0(RequestTransformContext requestContext) in /src/Azure.OpenAI.ChargebackProxy/ReverseProxy/OpenAIChargebackTransformProvider.cs:line 57
         at Yarp.ReverseProxy.Transforms.Builder.StructuredTransformer.TransformRequestAsync(HttpContext httpContext, HttpRequestMessage proxyRequest, String destinationPrefix, CancellationToken cancellationToken)
         at Yarp.ReverseProxy.Forwarder.HttpForwarder.CreateRequestMessageAsync(HttpContext context, String destinationPrefix, HttpTransformer transformer, ForwarderRequestConfig requestConfig, Boolean isStreamingRequest, ActivityCancellationTokenSource activityToken)
         at Yarp.ReverseProxy.Forwarder.HttpForwarder.SendAsync(HttpContext context, String destinationPrefix, HttpMessageInvoker httpClient, ForwarderRequestConfig requestConfig, HttpTransformer transformer, CancellationToken cancellationToken)
fail: Microsoft.AspNetCore.Server.Kestrel[13]
      Connection id "0HN07NNSGJGQV", Request id "0HN07NNSGJGQV:00000003": An unhandled exception was thrown by the application.
      System.NullReferenceException: Object reference not set to an instance of an object.
         at Azure.OpenAI.ChargebackProxy.ReverseProxy.OpenAIChargebackTransformProvider.<Apply>b__8_1(ResponseTransformContext responseContext) in /src/Azure.OpenAI.ChargebackProxy/ReverseProxy/OpenAIChargebackTransformProvider.cs:line 63
         at Yarp.ReverseProxy.Transforms.Builder.StructuredTransformer.TransformResponseAsync(HttpContext httpContext, HttpResponseMessage proxyResponse, CancellationToken cancellationToken)
         at Yarp.ReverseProxy.Forwarder.HttpForwarder.<>c__DisplayClass13_0.<<HandleRequestFailureAsync>g__ReportErrorAsync|0>d.MoveNext()
      --- End of stack trace from previous location ---
         at Yarp.ReverseProxy.Forwarder.HttpForwarder.HandleRequestFailureAsync(HttpContext context, StreamCopyHttpContent requestContent, Exception requestException, HttpTransformer transformer, ActivityCancellationTokenSource requestCancellationSource, Boolean failedDuringRequestCreation)
         at Yarp.ReverseProxy.Forwarder.HttpForwarder.SendAsync(HttpContext context, String destinationPrefix, HttpMessageInvoker httpClient, ForwarderRequestConfig requestConfig, HttpTransformer transformer, CancellationToken cancellationToken)
         at Yarp.ReverseProxy.Forwarder.ForwarderMiddleware.Invoke(HttpContext context)
         at Yarp.ReverseProxy.Health.PassiveHealthCheckMiddleware.Invoke(HttpContext context)
         at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
         at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.ProcessRequests[TContext](IHttpApplication`1 application)
info: Yarp.ReverseProxy.Forwarder.HttpForwarder[9]
      Proxying to https://cog-5lkddduydtyxi-swedencentral.openai.azure.com/openai/deployments/gpt-35-turbo/chat/completions?api-version=2023-09-01-preview HTTP/2 RequestVersionOrLower 
info: Yarp.ReverseProxy.Forwarder.HttpForwarder[56]
      Received HTTP/2.0 response 415.
warn: Yarp.ReverseProxy.Forwarder.HttpForwarder[48]
      ResponseHeaders: The destination returned a response that cannot be proxied back to the client.
      System.Text.Json.JsonException: 'U' is an invalid start of a value. Path: $ | LineNumber: 0 | BytePositionInLine: 0.
       ---> System.Text.Json.JsonReaderException: 'U' is an invalid start of a value. LineNumber: 0 | BytePositionInLine: 0.
         at System.Text.Json.ThrowHelper.ThrowJsonReaderException(Utf8JsonReader& json, ExceptionResource resource, Byte nextByte, ReadOnlySpan`1 bytes)
         at System.Text.Json.Utf8JsonReader.ConsumeValue(Byte marker)
         at System.Text.Json.Utf8JsonReader.ReadFirstToken(Byte first)
         at System.Text.Json.Utf8JsonReader.ReadSingleSegment()
         at System.Text.Json.Utf8JsonReader.Read()
         at System.Text.Json.Serialization.JsonConverter`1.ReadCore(Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state)
         --- End of inner exception stack trace ---
         at System.Text.Json.ThrowHelper.ReThrowWithPath(ReadStack& state, JsonReaderException ex)
         at System.Text.Json.Serialization.JsonConverter`1.ReadCore(Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state)
         at System.Text.Json.JsonSerializer.ReadFromSpan[TValue](ReadOnlySpan`1 utf8Json, JsonTypeInfo`1 jsonTypeInfo, Nullable`1 actualByteCount)
         at System.Text.Json.JsonSerializer.ReadFromSpan[TValue](ReadOnlySpan`1 json, JsonTypeInfo`1 jsonTypeInfo)
         at Azure.OpenAI.ChargebackProxy.ReverseProxy.OpenAIChargebackTransformProvider.<Apply>b__8_1(ResponseTransformContext responseContext) in /src/Azure.OpenAI.ChargebackProxy/ReverseProxy/OpenAIChargebackTransformProvider.cs:line 107
         at Yarp.ReverseProxy.Transforms.Builder.StructuredTransformer.TransformResponseAsync(HttpContext httpContext, HttpResponseMessage proxyResponse, CancellationToken cancellationToken)
         at Yarp.ReverseProxy.Forwarder.HttpForwarder.SendAsync(HttpContext context, String destinationPrefix, HttpMessageInvoker httpClient, ForwarderRequestConfig requestConfig, HttpTransformer transformer, CancellationToken cancellationToken)
fail: Microsoft.AspNetCore.Server.Kestrel[13]
      Connection id "0HN07NNSGJGR0", Request id "0HN07NNSGJGR0:00000001": An unhandled exception was thrown by the application.
      System.InvalidOperationException: The response cannot be cleared, it has already started sending.
         at Microsoft.AspNetCore.Http.ResponseExtensions.Clear(HttpResponse response)
         at Yarp.ReverseProxy.Forwarder.HttpForwarder.SendAsync(HttpContext context, String destinationPrefix, HttpMessageInvoker httpClient, ForwarderRequestConfig requestConfig, HttpTransformer transformer, CancellationToken cancellationToken)
         at Yarp.ReverseProxy.Forwarder.ForwarderMiddleware.Invoke(HttpContext context)
         at Yarp.ReverseProxy.Health.PassiveHealthCheckMiddleware.Invoke(HttpContext context)
         at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
         at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.ProcessRequests[TContext](IHttpApplication`1 application)
```

**Comment by iMicknl** [comment]
Seems that Python V1 SDK uses `Bearer {token value}` as the Authorization header. Python SDK v1 works with my OpenAI resource directly, but not with this APIM project.

**Comment by azureholic** [comment]
Python library seems to add an auth header
Added a line in the proxyserver to remove any existing auth header, before injecting the Managed Identity Token. ProxyServer uses MI for auth against AzureOpenAI

please retry 'azd deploy'

**Comment by iMicknl** [comment]
Thanks for the quick fix, @azureholic! This should be the culprit indeed, will verify later :).

**Comment by azureholic** [comment]
discovered and fixed this already this afternoon in my own repo - my own Python test had the same error.... 

https://github.com/azureholic/Azure.OpenAI

**Comment by iMicknl** [comment]
Works indeed! Tested normal ChatCompletion + Streaming via SDK v1.
